#!/bin/bash

set -u

TAPEDIR=$(dirname $0)

TOOLKIT=${1:-}

if [[ -z $TOOLKIT ]]; then
    echo "Usage: run TOOLKIT [TCONF]"
    echo "where TOOLKIT is one of {sockeye,fairseq}."
    echo "TCONF defaults to ./TOOLKIT.tconf."
    exit 1
fi
shift

TAPEFILE=$TAPEDIR/$TOOLKIT.tape
if [[ ! -e $TAPEFILE ]]; then
    echo "Fatal: Couldn't find toolkit tape file $TAPEFILE"
    exit 1
fi

TCONF=${1:-}
if [[ ! -e $TCONF ]]; then
    echo "Fatal: Couldn't find $TCONF"
    exit 1
fi
shift

DUCTTAPE=$(which ducttape)
if [[ $? -ne 0 ]]; then
   echo "Can't find ducttape."
   exit 1
fi

${DUCTTAPE} ${TAPEFILE} -C ${TCONF} $@
